{% set version="1.1.0" %}
{% set revision="17ff24ffd7a279dd6dd62a0fdee13cd3d1abfc64" %}

package:
  name: tauari 
  version: {{ version }}

source:
  git_url: https://github.com/quadram-institute-bioscience/tauari.git
  git_rev: {{ revision }}
  md5: unused

build:
  number: 0
  skip: true # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - automake
    - make
    - check
  host:
    - check
    - zlib
  run:
    - zlib

test:
  commands:
    - tauari -h 

about:
  home: https://github.com/quadram-institute-bioscience/tauari
  license: 'GPLv3'
  summary: 'Python bindings for phylogenetic library biomcmc-lib'

extra:
  identifiers:
    - biotools:tauari
  skip-lints:
    - uses_git_url
