language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
 
git:
  submodules: true
#install: make get-deps  # 
compiler:
  - gcc
before_install:
  - export OMP_NUM_THREADS=4 
  - sudo apt-get update
  - sudo apt-get install -y check 
  - sudo apt-get install -y autotools-dev 
  - sudo apt-get install -y python-dev 
install: 
  - autoreconf
script:
  - pip install -r requirements.txt
  - pip install .

branches:
  only:
  - master

# the Default script is "./configure && make && make test"

