name: tauari 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - setuptools 
  - python>=3.6 # includes python-dev
  - treeswift>=1.0 
  - automake
  - make
  - zlib
  - automake
  - check
  - pip:
    - .  # this means run pip on this directory's setup.py 
